### PR TITLE
add es-shims polyfill

### PR DESCRIPTION
**Pull request by ljharb**

### CODE REVIEW

**Comment by zloirock** [comment]
Maybe better sort them by popularity (or at least alphabetical)? -)

**Comment by cap-errouissi** [comment]
TU KO

**Review by michaelficarra — APPROVED** [review]

**Comment by zloirock** [comment]
Sorry, @michaelficarra, maybe you could say, why you add 👎 to my comment? In which moment `es-shims` version of `Promise.any` is first? Date of creation, publication, adding to this repo, popularity or at least alphabetical? Nothing. Something else? Or personal preferences?

**Comment by mathiasbynens** [comment]
We’ve had this discussion elsewhere. `goto` https://github.com/tc39/proposal-string-replaceall/pull/31#issuecomment-546583050

**Review by mathiasbynens — APPROVED** [review]

**Pull request merged**
