### PR TITLE
Remove AggregateError.prototype.toString

### PR DESCRIPTION
**Pull request by devsnek**
Refs https://github.com/tc39/proposal-promise-any/issues/36

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]
LGTM. (This section was originally added because the first draft meant to specify the error message differently. However, instead this should be done through the already-implementation-defined value of the `message` property, which is a change we made later. Nowadays, the section indeed seems redundant.)

I’ll wait for @chicoxyzzy’s review before merging.

**Review by bakkot — APPROVED** [review]
Note that the two functions are not *totally* identical, in that

```js
let error = new AggregateError([]);
error.name = void 0;
error.toString();
```
would prior to this change have given "AggregateError" and after it will give "Error".

I don't think anyone will ever notice that without starting from the spec, though, and since no other error type has that behavior anyway this seems an improvement.

**Comment by mathiasbynens** [comment]
@bakkot Great catch!

**Review by ljharb — APPROVED** [review]

**Review by chicoxyzzy — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
Thank you!

**Comment by anba** [comment]
CC @leobalter because test262 requires updates after this change.

The following tests probably need to be updated:
 -   test262/built-ins/AggregateError/prototype/toString/get-message-undefined.js
  -  test262/built-ins/AggregateError/prototype/toString/get-name-empty-string.js
   - test262/built-ins/AggregateError/prototype/toString/get-name-undefined.js
-    test262/built-ins/AggregateError/prototype/toString/prop-desc.js

And while there these two tests also need fixes (they call AggregateError without an iterable argument, resulting in throwing a TypeError).
 -   test262/built-ins/AggregateError/newtarget-proto-custom.js
 -   test262/built-ins/AggregateError/newtarget-proto-fallback.js

These six tests failed when running test262 with the [`Promise.any` patch for SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1568903) (currently under review).

**Comment by leobalter** [comment]
I'm removing tests for AggregateError#toString and adding one that asserts instances will point to Error#toString.

**Comment by leobalter** [comment]
@anba New patches for Test262 should fix these. PTAL?

**Pull request merged**
